POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName":"koshika",
    "email":"abcd@",
    "password":"charan"
}
###
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
    "email":"abcd@",
    "password":"charan",
    "role":"user"
}


###
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName":"koshika",
    "email":"abcd@",
    "password":"charan"
}
###
POST http://localhost:4000/author-api/login
Content-Type: application/json

{
    "email":"abcd@",
    "password":"charan",
    "role":"author"
}
###
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "title":"first article",
    "content":"this is my first article",
    "author":"69899c25b94eafa1332de774",
    "category":"technology"
}
###
PUT http://localhost:4000/author-api/articles/6989a8be1c29f16be3531aeb/author/69899c25b94eafa1332de774
Content-Type: application/json

{
    "title":"first article updated",
    "content":"this is my first article updated",
        "category":"technology"
}
###read articles author
GET http://localhost:4000/author-api/articles/69899c25b94eafa1332de774



###soft delete article
PUT http://localhost:4000/author-api/articles/6989a8be1c29f16be3531aeb
###
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "articleId":"989a8be1c29f16be3531aeb",
    "title":"first article updated again",
    "content":"this is my first article updated again",
        "category":"technology"
}

###logout 
GET http://localhost:4000/common-api/logout



###read all articles
GET http://localhost:4000/user-api/articles


###test req
GET http://localhost:4000/test

###block user
PUT http://localhost:4000/admin-api/block/69899c16b94eafa1332de771

###unblock user
PUT http://localhost:4000/admin-api/unblock/69899c16b94eafa1332de771

###update password
PUT http://localhost:4000/common-api/update-password
Content-Type: application/json

{
    "email":"abcd@",
    "oldPassword":"charan",
    "newPassword":"koshi@116"
}
